services:
  skrambl:
    container_name: skrambl
    env_file:
      - .env
    build: .
    expose:
      - ${DENO_PORT:?error}
    networks:
      - network
    healthcheck:
      test: ["CMD", "deno", "eval", "try { await fetch('http://127.0.0.1:${DENO_PORT:?error}') } catch { Deno.exit(1) }"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    attach: false
    read_only: true
    security_opt:
      - no-new-privileges:true

networks:
  network:
    name: ${COMPOSE_NETWORK:?error}
    external: true
